apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: doctor-appointment-system-git
  namespace: kkrishnavamshi518-dev
spec:
  template:
    spec:
      containers:
        - name: doctor-appointment-system-git
          image: image-registry.openshift-image-registry.svc:5000/kkrishnavamshi518-dev/doctor-appointment-system-git:latest
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: mysql-service
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: doctor_db
            - name: DB_USERNAME
              value: userIXX
            - name: DB_PASSWORD
              value: 6uDXRa0xObiMk2aj
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          ports:
            - containerPort: 8080